# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #name: Pool1
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: Buildpetstoreapp
        steps:
            #- task: DockerInstaller@0
             # inputs:
              #   dockerVersion: '17.09.0-ce'

            - task: Docker@2
              inputs:
                containerRegistry: 'ACRSVC'
                repository: 'petsroteapp'
                command: 'buildAndPush'
                Dockerfile: '$(System.DefaultWorkingDirectory)/petstore/petstoreapp/Dockerfile'
                tags: |
                  $(tag)
  - stage: Deploytowebapp
    jobs:
      - job: DeployPetstoreapp
        steps:
           
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Free Trial(e1f99b09-6d33-48df-bb4e-37349ec2de67)'
              appName: 'petstoreuk'
              containers: 'petstoreacruk.azurecr.io/petsroteapp:latest'
